-- MySQL Script generated by MySQL Workbench
-- Wed Dec 30 22:17:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Clup_engsw2020
-- -----------------------------------------------------
-- Database progetto d'esame del corso di Ingegneria del Software 
-- Anno Accademico 2020-2021
DROP SCHEMA IF EXISTS `Clup_engsw2020` ;

-- -----------------------------------------------------
-- Schema Clup_engsw2020
--
-- Database progetto d'esame del corso di Ingegneria del Software 
-- Anno Accademico 2020-2021
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Clup_engsw2020` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `Clup_engsw2020` ;

-- -----------------------------------------------------
-- Table `Clup_engsw2020`.`Booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Clup_engsw2020`.`Booking` ;

CREATE TABLE IF NOT EXISTS `Clup_engsw2020`.`Booking` (
  `idBooking` INT NOT NULL AUTO_INCREMENT,
  `Number` INT NOT NULL,
  `ArrivalTime` DATETIME NOT NULL,
  `FinishTime` DATETIME NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idBooking`),
  UNIQUE INDEX `number_UNIQUE` (`Number` ASC) VISIBLE,
  INDEX `idUser_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `Clup_engsw2020`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clup_engsw2020`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Clup_engsw2020`.`Category` ;

CREATE TABLE IF NOT EXISTS `Clup_engsw2020`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clup_engsw2020`.`CategoryInBooking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Clup_engsw2020`.`CategoryInBooking` ;

CREATE TABLE IF NOT EXISTS `Clup_engsw2020`.`CategoryInBooking` (
  `idCategoryInBooking` INT NOT NULL AUTO_INCREMENT,
  `idCategory` INT NOT NULL,
  `idBooking` INT NOT NULL,
  PRIMARY KEY (`idCategoryInBooking`),
  INDEX `idBooking_idx` (`idBooking` ASC) VISIBLE,
  INDEX `idCategory_idx` (`idCategory` ASC) INVISIBLE,
  CONSTRAINT `idBooking`
    FOREIGN KEY (`idBooking`)
    REFERENCES `Clup_engsw2020`.`Booking` (`idBooking`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idCategory`
    FOREIGN KEY (`idCategory`)
    REFERENCES `Clup_engsw2020`.`Category` (`idCategory`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clup_engsw2020`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Clup_engsw2020`.`Role` ;

CREATE TABLE IF NOT EXISTS `Clup_engsw2020`.`Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clup_engsw2020`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Clup_engsw2020`.`User` ;

CREATE TABLE IF NOT EXISTS `Clup_engsw2020`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `BirthdayDate` DATE NOT NULL,
  `Sesso` VARCHAR(1) NOT NULL,
  `TelephoneNumber` VARCHAR(11) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `idRole` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `idRole_idx` (`idRole` ASC) VISIBLE,
  CONSTRAINT `idRole`
    FOREIGN KEY (`idRole`)
    REFERENCES `Clup_engsw2020`.`Role` (`idRole`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
